### ISSUE TITLE
Exception loading the Mod Menu entrypoint for Illuminations

### ISSUE THREAD

**Issue by JLUsr** [MrCrayfish/Menulogue#1]
_Catalogue_ crashes when opening if _Illuminations_ is installed. Considering that the crash log
 states `Exception while loading entries for entrypoint 'modmenu' provided by 'illuminations'`, I thought this issue belonged here.
 
 MC 1.19.2 | Fabric API 0.61.0 | Illuminations 1.10.8 | Catalogue 1.6.3 | Menulogue 1.0.0

**Comment by MrCrayfish** [comment]
Thanks for the report, and the problem was in Menulogue. It also seems Illuminations defines a entrypoint for ModMenu but it's pointing to a non-existent implementation. Seems they removed it in 1.19

**Comment by MrCrayfish** [comment]
Fixed in 1.0.1
