### ISSUE TITLE
Menulogue leaves a button with no text which goes to the Mod Menu

### ISSUE THREAD

**Issue by DevXYZROBLOX** [MrCrayfish/Menulogue#4]
The Mod Menu button is still there along with the Catalogue one but the Mod Menu button has no text.

**Comment by MrCrayfish** [comment]
If you're going to use Catalogue, you don't need Mod Menu or vice versa. If you want configs that are designed to work with Mod Menu to work with Catalogue, you'll need to install Menulogue addon.
